# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://oakgarelik.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Oak Garelik Grangé - Portfolio"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Oak Garelik Grangé
author-bio: Computer Engineering student at the Polytechnic Faculty of the National University of Asunción  # change to false to hide
author-image: gray_wolf_games_-_logo.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: About
- text: Education
  permalink: Education
- text: My objective
  permalink: My objective

# use false to turn off any social media links
twitter: false
facebook: false
instagram: https://instagram.com/oakgg25
github: https://github.com/oakgarelik
linkedin: https://www.linkedin.com/in/oak-garelik-grange-0270b6280/


# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages


# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
