# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://harrywang.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Tailpages: Tailwind + Github Pages"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Oak Garelik Grangé
author-bio: Computer Engineering student at the Polytechnic Faculty of the National University of Asunción  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false #https://twitter.com/
facebook: false #https://facebook.com/
instagram: https://instagram.com/oakgg25
github: https://github.com/AwolfTwoFive
linkedin: https://linkedin.com/oak-garelik-grangé-0270b6280
medium: false
google-scholar: false
phoneNumber: "+59599150619"
email: awolftwofive@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
